V2/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
]

V2/bio_et_terre/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path, path

from store import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('administration/', include('administration.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [re_path(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

V2/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('account/', views.account, name="account"),
    path('histCommande/<int:id>', views.historiqueCommande, name="historiqueCommande"),
    path('panier/', views.panier, name="panier"),
    path('panierModifQtt/', views.panierModifierQuantite, name="panierModifierQuantite"),
    path('rayons/', views.rayons, name="rayons"),
    path('rayons/<int:id>', views.rayons_listing, name="rayon_listing"),
    path('recherche/', views.recherche, name="recherche"),
    path('produit/<str:id>', views.produit_detail, name="produit_detail"),
]

V2/accounts/models.py
from django.contrib.auth.models import AbstractUser

class Utilisateur(AbstractUser):
    pass

V2/store/models.py
# Create your models here.
from django.db import models

from accounts.models import Utilisateur


class Categorie(models.Model):
    nom = models.CharField(max_length=100)
    taux_tva = models.FloatField()
    image = models.URLField()


class Marque(models.Model):
    nom = models.CharField(max_length=100)


class Type(models.Model):
    nom = models.CharField(max_length=1000)
    unite_mesure = models.CharField(max_length=100)
    mesure = models.CharField(max_length=100)
    unite_mesure_petit = models.CharField(max_length=100)
    mesure_petit = models.CharField(max_length=100)


class Produit(models.Model):
    id = models.CharField(primary_key=True, max_length=100)
    nom = models.CharField(max_length=1000)
    prix = models.FloatField()
    stock = models.IntegerField()
    description = models.CharField(max_length=10000)
    image = models.URLField(max_length=1000)
    achetable = models.BooleanField(default=True)
    quantite = models.FloatField()
    marque = models.ForeignKey(Marque, db_column="id_marque", on_delete=models.DO_NOTHING)
    categorie = models.ForeignKey(Categorie, db_column='id_categorie', on_delete=models.DO_NOTHING)
    type = models.ForeignKey(Type, db_column='id_type', on_delete=models.DO_NOTHING)

    @property
    def calcTVA(self):
        return round((1 + self.categorie.taux_tva/100) * self.prix, 2)

    @property
    def getPoids(self):
        if self.type.id == 1:
            resultat = "Unité"
        else:
            if self.quantite < 1:
                if self.type.id == 2:
                        quantite = self.quantite * 1000
                elif self.type.id == 3:
                    quantite = self.quantite * 100
                mesure = self.type.mesure_petit
            else:
                quantite = self.quantite
                mesure = self.type.mesure

            if quantite - int(quantite) == 0:
                quantite = int(quantite)

            resultat = f"{quantite}{mesure}"

        return resultat

    @property
    def calcPrixPoids(self):
        if self.type.id == 1:
            resultat = f"{self.calcTVA}€/Unité"
        else:
            prix = round(self.calcTVA / self.quantite, 2)
            resultat = f"{prix}€/{self.type.mesure}"

        return resultat

class Commande(models.Model):
    id = models.AutoField(primary_key=True)
    utilisateur = models.ForeignKey(Utilisateur, db_column='id_utilisateur', on_delete=models.DO_NOTHING, blank=True, null=True)
    date_commande = models.DateTimeField(auto_now_add=True)
    est_complete = models.BooleanField(default=False)

    @property
    def get_cart_total(self):
        produits = Commande_Produit.objects.filter(commande=self).order_by('produit__id')
        return round(sum([produit.calcPrixTotal for produit in produits]), 2)

    @property
    def get_cart_items(self):
        produits = Commande_Produit.objects.filter(commande=self).order_by('produit__id')
        return sum([produit.quantite for produit in produits])


class Commande_Produit(models.Model):
    id = models.AutoField(primary_key=True)
    commande = models.ForeignKey(Commande, db_column='id_commande', on_delete=models.DO_NOTHING, blank=True, null=True)
    produit = models.ForeignKey(Produit, db_column='id_produit', on_delete=models.DO_NOTHING, blank=True, null=True)
    quantite = models.IntegerField()

    @property
    def calcPrixTotal(self):
        return round(self.quantite * self.produit.prix, 2)

V2/accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, login, authenticate, logout
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.shortcuts import render, redirect

User = get_user_model()
# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == "POST":
        valide = True
        firstname = request.POST.get("firstname")
        lastname = request.POST.get("lastname")
        email = request.POST.get("email")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")

        try:
            validate_email(email)
        except ValidationError as error:
            valide = False
            for e in error:
                messages.error(request, e)

        queryUser = User.objects.filter(email=email)
        if queryUser:
            valide = False
            messages.error(request, "Cette adresse mail est déjà utilisée.")

        if password != confirm_password:
            valide = False
            messages.error(request, "Saisissez deux fois le même mot de passe.")

        if valide:
            user = User.objects.create_user(username=email, password=password, first_name=firstname, last_name=lastname, email=email)
            login(request, user)
            return redirect('index')

    return render(request, 'accounts/signup.html')


def login_user(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        queryUser = User.objects.filter(email=email)
        if queryUser:
            user = authenticate(username=email, password=password)
            if user:
                login(request, user)
                return redirect('index')
            else:
                messages.error(request, "Mauvais mot de passe.")
        else:
            messages.error(request, "Aucun compte ne correspond à cette adresse mail.")

    return render(request, 'accounts/login.html')


def logout_user(request):
    logout(request)
    return redirect('index')

V2/store/views.py
import datetime
import json
import random

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.template import loader

from store.models import Produit, Categorie, Commande, Commande_Produit

User = get_user_model()


@login_required()
def account(request):
    client = User.objects.get(id=request.user.id)
    commandes = Commande.objects.filter(utilisateur=request.user.id, est_complete=1).order_by("id")

    template = loader.get_template("store/account.html")
    context = {
        'client': client,
        'commandes': commandes
    }

    return HttpResponse(template.render(context, request=request))

@login_required()
def historiqueCommande(request, id):
    commande = get_object_or_404(Commande, id=id, utilisateur=request.user.id, est_complete=1)
    produits = Commande_Produit.objects.filter(commande=commande).order_by('produit__categorie')

    template = loader.get_template("store/historiqueCommande.html")
    context = {
        "commande": commande,
        "produits": produits
    }
    return HttpResponse(template.render(context, request=request))

def index(request):
    if request.user.is_superuser:
        return redirect('administration:index')

    prods = Produit.objects.order_by("id")
    produits = []
    already_took = []
    for i in range(5):
        rand = random.randrange(0, len(prods))
        while rand in already_took or prods[rand].achetable == 0:
            rand = random.randrange(0, len(prods))

        already_took.append(rand)
        produits.append(prods[rand])

    template = loader.get_template("store/index.html")
    context = {
        "produits": produits
    }

    return HttpResponse(template.render(context, request=request))

def panier(request):
    if request.user.is_authenticated:
        client = User.objects.get(id=request.user.id)

        commande = Commande.objects.get_or_create(utilisateur=client, est_complete=0)[0]
        produits = Commande_Produit.objects.filter(commande=commande).order_by('produit__categorie')

        if request.method == "POST":
            for comp in produits:
                prod = comp.produit
                prod.stock = prod.stock - comp.quantite
                prod.save()

            commande.est_complete = 1
            date = datetime.datetime.now()
            commande.date_commande = date.strftime("%Y-%m-%d %H:%M:%S")
            commande.save()

            sujet = "Merci pour votre commande !"
            message = """<!DOCTYPE html>
                                    <html lang="en">

                                    <head>
                                        <meta charset="UTF-8">
                                        <meta http-equiv="X-UA-Compatible" content="IE=edge">
                                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                        <title>Merci pour votre commande !</title>
                                        <style>
                                            .box-element {
                                                box-shadow: hsl(0, 0%, 80%) 0 0 16px;
                                                background-color: #fff;
                                                border-radius: 4px;
                                                padding: 10px;
                                            }

                                            .row-image {
                                                width: 100px;
                                            }

                                            .cart-row {
                                                display: flex;
                                                align-items: flex-stretch;
                                                padding-bottom: 10px;
                                                margin-bottom: 10px;
                                                border-bottom: 1px solid #ececec;

                                            }

                                            .quantity {
                                                display: inline-block;
                                                font-weight: 700;
                                                padding-right: 10px;


                                            }

                                            .chg-quantity {
                                                width: 12px;
                                                cursor: pointer;
                                                display: block;
                                                margin-top: 5px;
                                                transition: .1s;
                                            }

                                            .chg-quantity:hover {
                                                opacity: .6;
                                            }

                                            table {
                                                table-layout: fixed;
                                                width: 100%;
                                            }

                                            td {
                                                text-align: center;
                                            }

                                            .bg-noir {
                                                color: #fff;
                                                background-color: black;
                                                text-align: center;
                                                padding: 2px;
                                            }

                                            .bg-gris {
                                                background-color: rgb(230, 230, 230);
                                                text-align: center;
                                                padding: 2px;
                                            }

                                            .container {
                                                padding: 10px;
                                            }

                                            h3 {
                                                text-align: left;
                                            }
                                        </style>
                                    </head> """ + f"""
                                    <body>
                                    <div class="bg-noir">
                                        <h1>Bio & Terre</h1>
                                    </div>
                                    <div class="bg-gris">
                                        <h2>VOTRE COMMANDE EST ENREGISTRÉE !</h2>

                                        <p>Bonjour {client.first_name.capitalize()}, votre commande a été reçue et nous vous en remercions.</p>
                                        <p>N° de commande: {commande.id}</p>
                                        <p>Date de la commande: {date.strftime("%d/%m/%Y")}</p>

                                        <div class="container">
                                            <div class="box-element">
                                                <h3>Détail de paiement :</h3>
                                                <table class="table">
                                                    <tr>
                                                        <th>
                                                            <h5>Articles: <strong>{commande.get_cart_items}</strong> dont {len(produits)} différents
                                                            </h5>
                                                        </th>
                                                        <th>
                                                            <h5>Total: <strong>{commande.get_cart_total}€</strong></h5>
                                                        </th>
                                                        <th></th>
                                                    </tr>
                                                </table>
                                            </div>

                                            <br>

                                            <div class="box-element">
                                                <h3>Détail de commande :</h3>
                                                <table>
                                                    <tr>
                                                        <th>Image</th>
                                                        <th>Article</th>
                                                        <th>Prix</th>
                                                        <th>Quantité</th>
                                                        <th>Total</th>
                                                    </tr>"""

            for commande_produit in produits:
                message += f"""
                            <tr>
                            <td><a href="{request.build_absolute_uri(f'/store/produit/{commande_produit.produit.id}')}"><img
                                        src="{commande_produit.produit.image}" alt="{commande_produit.produit.nom}" height="75"
                                        width="75"></a></td>
                            <td>
                                <p>{commande_produit.produit.nom}</p>
                            </td>
                            <td>
                                <p>{commande_produit.produit.prix}€</p>
                            </td>

V2/store/templates/store/account.html
{% extends 'store/base.html' %}

{% block title %}
Compte
{% endblock %}

{% block content %}
<div class="col-md-8 offset-md-2 py-3">
    <h2>Mon compte</h2>
    <hr>
    <div class="pb-3">
        Prénom
        <br>
        <input class="form-control" id="disabledInput" type="text" placeholder="{{ client.first_name|title }}" disabled>
    </div>
    <div class="pb-3">
        Nom
        <br>
        <input class="form-control" id="disabledInput" type="text" placeholder="{{ client.last_name|title }}" disabled>
    </div>
    <div class="pb-3">
        Adresse mail
        <br>
        <input class="form-control" id="disabledInput" type="text" placeholder="{{ client.email }}" disabled>
    </div>

    <div class="text-center">
        <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Me déconnecter</a>
    </div>
</div>

<div class="col-md-8 offset-md-2 py-3">
    <h2>Mes commandes</h2>
    <hr>
    {% if commandes %}
    <table class="table text-center table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Numéro de commande</th>
                <th>Date & Heure </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for commande in commandes %}
            <tr>
                <td>{{commande.id}}</td>
                <td>{{commande.date_commande}}</td>
                <td><a class="btn btn-dark" href="{% url 'store:historiqueCommande' commande.id %}">Consulter</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
    <div class="text-center py-3">
        Vous n'avez passé aucune commande pour le moment.
    </div>
    {% endif %}
</div>

{% endblock %}

V2/store/templates/store/base.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Bio&Terre - {% block title %}{% endblock %}</title>
  <link rel="icon" href="{% static 'store/images/logo.ico' %}" />
  {% block css %}{% endblock %}

  {% block scriptJs %}{% endblock %}
</head>

<body class="d-flex flex-column" style="min-height: 100vh;">
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'store/images/Logo_Blanc.png'%}" alt="Bio & Terre"
            width="75" height="75"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
          aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item px-2">
              <a class="nav-link {% block active_accueil %}{% endblock %}" href="{% url 'index' %}">Accueil</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link {% block active_rayons %}{% endblock %}" href="{% url 'store:rayons' %}">Rayons</a>
            </li>
            <li class="nav-item px-2">
              <form action="{% url 'store:recherche' %}" method="get">
                  <input class="form-control" name="query" type="text" placeholder="Rechercher..." aria-label="Search">
              </form>
            </li>
          </ul>
          <div class="d-inline-flex px-2">
            <a href="{% url 'store:panier' %}"><img src="{% static 'store/images/shopping-cart.png' %}" title="Panier" alt="Panier" height="30" width="30"></a>
          </div>
          {% if request.user.is_authenticated %}
          <div class="d-inline-flex px-2">
            <a href="{% url 'store:account' %}"><img src="{% static 'store/images/user.png' %}" title="Mon compte" alt="Mon Compte" height="30" width="30"></a>
          </div>
          {% else %}
          <div class="d-inline-flex bg-success rounded-pill">
            <a class="nav-link text-light" href="{% url 'accounts:login' %}">Se connecter</a>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

  <div class="container">
    <div class="row">
      {% block content %}{% endblock %}
    </div>
  </div>

  <footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <div>
        <p class="my-1 text-muted text-center">Site web réalisé à l'aide du framework Django par:</p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted text-center"
            href="mailto:mathieu.dary@etudiant.univ-rennes1.fr">mathieu.dary@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted text-center"
            href="mailto:erwann.gauthier@etudiant.univ-rennes1.fr">erwann.gauthier@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted"
            href="mailto:titouan.le-berre@etudiant.univ-rennes1.fr">titouan.le-berre@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted"
            href="mailto:yannis.ligot@etudiant.univ-rennes1.fr">yannis.ligot@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
    </div>
  </footer>


  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

  {% block linkJs %}{% endblock %}
</body>

</html>

V2/store/templates/store/historiqueCommande.html
{% extends 'store/base.html' %}
{% load static %}

{% block title %}
Historique Commande
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'store/css/style.css' %}">
{% endblock %}

{% block active_panier%}
active
{% endblock %}

{% block content %}
<div class="col-lg-12">
    <br>
    <br>

    <div class="box-element">
        <a class="btn btn-outline-dark" href="{% url 'store:account' %}">&#x2190; Retour sur mon profil</a>

        <br>
        <br>

        <table class="table">
            <tr>
                <th>
                    <h5>Articles: <strong>{{commande.get_cart_items}}</strong> dont {{produits.count}} différent{% if produits.count > 1 %}s{% endif %}</h5>
                </th>
                <th>
                    <h5>Total: <strong>{{commande.get_cart_total}}€</strong></h5>
                </th>
                <th>
                </th>
            </tr>
        </table>
    </div>

    <br>

    <div class="box-element">
        <div class="cart-row">
            <div style="flex:2"><strong>Image</strong></div>
            <div style="flex:2"><strong>Article</strong></div>
            <div style="flex:1"><strong>Prix</strong></div>
            <div style="flex:1"><strong>Quantité</strong></div>
            <div style="flex:1"><strong>Total</strong></div>
        </div>

        {% for commande_produit in produits %}
        <div class="cart-row">
            <div style="flex:2"><a href="{% url 'store:produit_detail' commande_produit.produit.id %}"><img
                        src="{{commande_produit.produit.image}}" alt="{{produit.id_produit.nom}}" height="75"
                        width="75"></a></div>
            <div style="flex:2">
                <p>{{commande_produit.produit.nom}}</p>
            </div>
            <div style="flex:1">
                <p>{{commande_produit.produit.prix}}€</p>
            </div>
            <div style="flex:1">
                <p class="quantity">{{commande_produit.quantite}}</p>
            </div>
            <div style="flex:1">
                <p>{{commande_produit.calcPrixTotal}}€</p>
            </div>
        </div>
        {% endfor %}
    </div>

    <br>
</div>

{% endblock %}

V2/store/templates/store/panier.html
{% extends 'store/base.html' %}
{% load static %}

{% block title %}
Panier
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'store/css/style.css' %}">
{% endblock %}

{% block scriptJs %}
<script type="text/javascript">
    var user = '{{request.user}}'

    function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrftoken = getToken('csrftoken');
    const urlUpdateItem = "{% url 'store:panierModifierQuantite'%}"
</script>
{% endblock %}

{% block active_panier%}
active
{% endblock %}

{% block content %}
<div class="col-lg-12">
    <br>
    <br>
    {% if messages %}
    <div class="alert alert-success">
    {% for message in messages %}
        {{message}}
        <br>
    {% endfor %}
    </div>
    {% endif %}
    <div class="box-element">
        <a class="btn btn-outline-dark" href="{% url 'store:rayons' %}">&#x2190; Continuer mes achats</a>

        <br>
        <br>

        <table class="table">
            <tr>
                <th>
                    <h5>Articles: <strong>{{commande.get_cart_items}}</strong> dont {{produits.count}} différent{% if produits.count > 1 %}s{% endif %}</h5>
                </th>
                <th>
                    <h5>Total: <strong>{{commande.get_cart_total}}€</strong></h5>
                </th>
                <th>
                    {% if user.is_authenticated %}
                    {% if produits %}
                    <form method="POST">
                        {% csrf_token %}
                        <button class="btn btn-success" type="submit">
                            Payer
                        </button>
                    </form>
                    {% else %}
                    <a style="float:right; margin: 5px;" class="btn btn-secondary disabled" href="">Payer</a>
                    {% endif %}
                    {% else %}
                    <a href="{% url 'accounts:login' %}" class="btn btn-success">Se connecter</a>
                    {% endif %}
                </th>
            </tr>
        </table>
    </div>

    <br>

    <div class="box-element">
        {% if produits %}
        <div class="cart-row">
            <div style="flex:2"><strong>Image</strong></div>
            <div style="flex:2"><strong>Article</strong></div>
            <div style="flex:1"><strong>Prix</strong></div>
            <div style="flex:1"><strong>Quantité</strong></div>
            <div style="flex:1"><strong>Total</strong></div>
        </div>

        {% for commande_produit in produits %}
        <div class="cart-row">
            <div style="flex:2"><a href="{% url 'store:produit_detail' commande_produit.produit.id %}"><img
                        src="{{commande_produit.produit.image}}" alt="{{produit.id_produit.nom}}" height="75"
                        width="75"></a></div>
            <div style="flex:2">
                <p>{{commande_produit.produit.nom}}</p>
            </div>
            <div style="flex:1">
                <p>{{commande_produit.produit.prix}}€</p>
            </div>
            <div style="flex:1">
                <p class="quantity">{{commande_produit.quantite}}</p>
                <div class="quantity">
                    {% if commande_produit.quantite < commande_produit.produit.stock %} <img
                        data-product="{{commande_produit.produit.id}}" data-action="add"
                        src="{% static 'store/images/up-arrow.png' %}" alt="" class="chg-quantity update-cart">
                        {% endif %}
                        <img data-product="{{commande_produit.produit.id}}" data-action="delete"
                            src="{% static 'store/images/down-arrow.png' %}" alt="" class="chg-quantity update-cart">
                </div>
            </div>
            <div style="flex:1">
                <p>{{commande_produit.calcPrixTotal}}€</p>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="cart-row justify-content-md-center">
            <p><strong>Votre panier est vide !</strong></p>
        </div>
        {% endif %}
    </div>

    <br>
</div>

{% endblock %}

{% block linkJs %}
<script type="text/javascript" src="{% static 'store/js/cart.js' %}"></script>
{% endblock %}