V2/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
]

V2/administration/urls.py
from django.urls import path

from . import views

app_name = 'administration'

urlpatterns = [
    path('index/', views.index, name="index"),

    path('categories/', views.categories, name='categories'),
    path('categories/ajouter/', views.categories_ajouter, name='categories_ajouter'),
    path('categories/modif/<str:id>/', views.categories_modifier, name='categories_modifier'),
    path('categories/suppr/<str:id>/', views.categories_supprimer, name='categories_supprimer'),

    path('clients/', views.clients, name="clients"),

    path('marques/', views.marques, name='marques'),
    path('marques/ajouter/', views.marques_ajouter, name='marques_ajouter'),
    path('marques/modif/<str:id>/', views.marques_modifier, name='marques_modifier'),
    path('marques/suppr/<str:id>/', views.marques_supprimer, name='marques_supprimer'),

    path('produits/', views.produits, name="produits"),
    path('produits/ajouter/', views.produits_ajouter, name="produits_ajouter"),
    path('produits/<str:id>/', views.produits_detail, name='produits_detail'),
    path('produits/modif/<str:id>/', views.produits_modifier, name='produits_modifier'),
    path('produits/modif_stock/<str:id>/', views.produits_modifier_stock, name='produits_modifier_stock'),
    path('produits/suppr/<str:id>/', views.produits_supprimer, name='produits_supprimer'),
]

V2/bio_et_terre/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path, path

from store import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('administration/', include('administration.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [re_path(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

V2/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('account/', views.account, name="account"),
    path('histCommande/<int:id>', views.historiqueCommande, name="historiqueCommande"),
    path('panier/', views.panier, name="panier"),
    path('panierModifQtt/', views.panierModifierQuantite, name="panierModifierQuantite"),
    path('rayons/', views.rayons, name="rayons"),
    path('rayons/<int:id>', views.rayons_listing, name="rayon_listing"),
    path('recherche/', views.recherche, name="recherche"),
    path('produit/<str:id>', views.produit_detail, name="produit_detail"),
]

V2/administration/models.py
# Create your models here.

V2/administration/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Max
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.urls import reverse

from store.models import Marque, Produit, Categorie, Type

User = get_user_model()

@user_passes_test(lambda u: u.is_superuser)
def index(request):
    template = loader.get_template("administration/admin_index.html")

    context = {}

    return HttpResponse(template.render(context, request=request))


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    template = loader.get_template("administration/admin_categories.html")

    categories = Categorie.objects.all()
    context = {
        'categories': categories
    }

    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def categories_ajouter(request):
    if request.method == "POST":
        nom = request.POST.get("nom")
        taux_tva = request.POST.get("taux_tva")
        image = request.POST.get("image")
        categorie = Categorie.objects.get_or_create(nom=nom, taux_tva=taux_tva, image=image)
        return redirect('administration:categories')

    template = loader.get_template("administration/admin_categories_ajouter.html")
    context = {}
    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def categories_modifier(request, id):
    categorie = get_object_or_404(Categorie, id=id)

    if request.method == "POST":
        nom = request.POST.get("nom")
        taux_tva = float(request.POST.get("taux_tva"))
        image = request.POST.get("image")
        if categorie.nom != nom or categorie.taux_tva != taux_tva or categorie.image != image:
            categorie.nom = nom
            categorie.taux_tva = taux_tva
            categorie.image = image
            categorie.save()
            return redirect('administration:categories')
        else:
            messages.error(request, "Vous n'avez pas modifié la catégorie.")

    template = loader.get_template("administration/admin_categories_modif.html")
    context = {
        'categorie': categorie
    }
    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def categories_supprimer(request, id):
    categorie = get_object_or_404(Categorie, id=id)

    if request.method == "POST":
        categorie.delete()
        return redirect('administration:categories')

    template = loader.get_template("administration/admin_categories_delete.html")
    produits = Produit.objects.filter(categorie=categorie)
    context = {
        'categorie': categorie,
        'produits': produits
    }
    return HttpResponse(template.render(context, request=request))


@user_passes_test(lambda u: u.is_superuser)
def clients(request):
    template = loader.get_template("administration/admin_clients.html")

    clients = User.objects.filter(is_superuser=0).order_by("id")
    context = {
        'clients': clients
    }

    return HttpResponse(template.render(context, request=request))


@user_passes_test(lambda u: u.is_superuser)
def marques(request):
    template = loader.get_template("administration/admin_marques.html")

    marques = Marque.objects.all()
    context = {
        'marques': marques
    }

    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def marques_ajouter(request):
    if request.method == "POST":
        nom = request.POST.get("nom")
        marque = Marque.objects.get_or_create(nom=nom)
        return redirect('administration:marques')

    template = loader.get_template("administration/admin_marques_ajouter.html")
    context = {}
    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def marques_modifier(request, id):
    marque = get_object_or_404(Marque, id=id)

    if request.method == "POST":
        nom = request.POST.get("nom")
        if marque.nom != nom:
            marque.nom = nom
            marque.save()
            return redirect('administration:marques')
        else:
            messages.error(request, "Vous n'avez pas modifié la marque.")

    template = loader.get_template("administration/admin_marques_modif.html")
    context = {
        'marque': marque
    }
    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def marques_supprimer(request, id):
    marque = get_object_or_404(Marque, id=id)

    if request.method == "POST":
        marque.delete()
        return redirect('administration:marques')

    template = loader.get_template("administration/admin_marques_delete.html")
    produits = Produit.objects.filter(marque=marque)
    context = {
        'marque': marque,
        'produits': produits
    }
    return HttpResponse(template.render(context, request=request))


@user_passes_test(lambda u: u.is_superuser)
def produits(request):
    template = loader.get_template("administration/admin_produits.html")
    produits = Produit.objects.filter(achetable=1).order_by("categorie__id")
    context = {
        'produits': produits
    }
    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def produits_detail(request, id):
    template = loader.get_template("administration/admin_produits_detail.html")
    produit = Produit.objects.get(pk=id)
    if produit.type.id != 1 and produit.quantite < 1:
        if produit.type.id == 2:
            quantite = produit.quantite * 1000
        elif produit.type.id == 3:
            quantite = produit.quantite * 100
        mesure = produit.type.mesure_petit
        prix = round(produit.calcTVA / produit.quantite, 2)
        context = {
            'produit': produit,
            'quantite':quantite,
            'mesure': mesure,
            'prix': prix
        }
    else:
        context = {
            'produit': produit,
            'prix': produit.calcTVA
        }
    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def produits_ajouter(request):
    if request.method == "POST":
        nom = request.POST.get("nom")
        prix = float(request.POST.get("prix"))
        stock = int(request.POST.get("stock"))
        description = request.POST.get("description")
        image = request.POST.get("image")

        marque_id = int(request.POST.get("marque"))
        if marque_id == -1:
            marque_nom = request.POST.get("marque_nom")
            marque = Marque.objects.get_or_create(nom=marque_nom)[0]
        else:
            marque = Marque.objects.get(pk=marque_id)

        categorie_id = int(request.POST.get("categorie"))
        if categorie_id == -1:
            categorie_nom = request.POST.get("categorie_nom")
            categorie_tva = float(request.POST.get("categorie_tva"))
            categorie_image = request.POST.get("categorie_image")
            categorie = Categorie.objects.get_or_create(nom=categorie_nom, taux_tva=categorie_tva, image=categorie_image)[0]
        else:
            categorie = Categorie.objects.get(pk=categorie_id)

        type_id = int(request.POST.get("type"))
        if type_id == 2:
            quantite = float(request.POST.get("solide"))
        elif type_id == 3:
            quantite = float(request.POST.get("liquide"))
        else:
            quantite = 0
        type = Type.objects.get(pk=type_id)

        id = Produit.objects.filter(categorie=categorie.id).aggregate(Max('id'))['id__max']
        if id:
            id = str(int(id[:id.find('_')]) + 1) + "_0"
        else:
            id = str(categorie.id * 10000 + 1) + "_0"

        produit = Produit.objects.get_or_create(id=id, nom=nom, prix=prix, stock=stock, description=description, image=image, categorie=categorie, marque=marque, type=type, quantite=quantite)
        return redirect('administration:produits')

    template = loader.get_template("administration/admin_produits_ajouter.html")
    marque = Marque.objects.all().order_by('nom')
    categorie = Categorie.objects.all().order_by('nom')
    type = Type.objects.all().order_by('nom')
    context = {
        'marques': marque,
        'categories': categorie,
        'types': type
    }
    return HttpResponse(template.render(context, request=request))

@user_passes_test(lambda u: u.is_superuser)
def produits_modifier(request, id):
    produit = get_object_or_404(Produit, id=id)

    if produit.achetable == 0:
        return redirect('administration:produits')

    if request.method == "POST":
        nom = request.POST.get("nom")
        prix = float(request.POST.get("prix"))
        stock = int(request.POST.get("stock"))
        description = request.POST.get("description")
        image = request.POST.get("image")
        marque_id = int(request.POST.get("marque"))
        categorie_id = int(request.POST.get("categorie"))
        type_id = int(request.POST.get("type"))
        if type_id == 2:
            quantite = float(request.POST.get("solide"))
        elif type_id == 3:
            quantite = float(request.POST.get("liquide"))
        else:
            quantite = 0

        if produit.nom != nom or produit.prix != prix or produit.stock != stock or produit.description != description or produit.image != image or produit.marque.id != marque_id or produit.categorie.id != categorie_id or produit.type.id != type_id or produit.quantite != quantite:
            if marque_id == -1:
                marque_nom = request.POST.get("marque_nom")
                marque = Marque.objects.get_or_create(nom=marque_nom)
            else:
                marque = Marque.objects.get(pk=marque_id)

            if categorie_id == -1:

V2/administration/templates/administration/admin_base.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Bio&Terre - ADMIN - {% block title %}{% endblock %}</title>
  <link rel="icon" href="{% static 'store/images/logo.ico' %}" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column" style="min-height: 100vh;">
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'administration:index' %}"><img src="{% static 'store/images/Logo_Blanc.png'%}"
            alt="Bio & Terre" width="75" height="75"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
          aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item px-2">
              <a class="nav-link {% block active_accueil %}{% endblock %}" href="{% url 'administration:index' %}">Accueil</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link {% block active_produits %}{% endblock %}" href="{% url 'administration:produits' %}">Produits</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link {% block active_categories %}{% endblock %}" href="{% url 'administration:categories' %}">Catégories</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link {% block active_marques %}{% endblock %}" href="{% url 'administration:marques' %}">Marques</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link {% block active_clients %}{% endblock %}" href="{% url 'administration:clients' %}">Clients</a>
            </li>
          </ul>
          {% if request.user.is_authenticated %}
          <div class="d-inline-flex bg-danger rounded-pill">
            <a class="nav-link text-light" href="{% url 'accounts:logout' %}">Se déconnecter</a>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

  <div class="container">
    <div class="row">
      {% block content %}{% endblock %}
    </div>
  </div>

  <footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <div>
        <p class="my-1 text-muted text-center">Site web réalisé à l'aide du framework Django par:</p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted text-center"
            href="mailto:mathieu.dary@etudiant.univ-rennes1.fr">mathieu.dary@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted text-center"
            href="mailto:erwann.gauthier@etudiant.univ-rennes1.fr">erwann.gauthier@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted"
            href="mailto:titouan.le-berre@etudiant.univ-rennes1.fr">titouan.le-berre@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted"
            href="mailto:yannis.ligot@etudiant.univ-rennes1.fr">yannis.ligot@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
    </div>
  </footer>


  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

  {% block script %}{% endblock %}
</body>

</html>

V2/administration/templates/administration/admin_categories_delete.html
{% extends 'administration/admin_base.html' %}

{% block title %}
Supprimer catégorie
{% endblock %}

{% block active_categories %}
active
{% endblock %}

{% block content %}
<div class="col-md-8 col-md-offset-2">
    <div class="py-3">
        <h3>Supprimer la catégorie: {{ categorie.nom }} </h3>
        <hr>
        {% if produits|length > 0 %}
        <div id="message_erreur" class="py-3 alert alert-danger">
            Vous ne pouvez pas supprimer la catégorie car elle est déjà utilisée par des produits.
        </div>
        {% else %}
        <div id="message_erreur" class="py-3 alert alert-warning">
            Etes-vous sûr de vouloir supprimer cette catégorie ?
        </div>
        <form method="POST">
            {% csrf_token %}
            <button id="btn-suppr" class="btn btn-outline-danger">Supprimer</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

V2/administration/templates/administration/admin_categories_modif.html
{% extends 'administration/admin_base.html' %}

{% block title %}
Modif catégorie
{% endblock %}

{% block active_categories %}
active
{% endblock %}

{% block content %}

<div class="col-md-8 offset-md-2 pt-5">
    <div class="py-3">
        <h3>Modifier la catégorie</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}

            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}

            <div class="pb-3">
                <label for="nom">Nom</label>
                <br>
                <input class="form-control" id="nom" type="text" name="nom"
                    placeholder="Entrer le nom de la catégorie..." autocomplete="off" required="required"
                    value="{{categorie.nom}}">
            </div>
            <div class="pb-3">
                <label for="nom">Taux TVA (en %)</label>
                <br>
                <input class="form-control" id="taux_tva" type="number" step="0.01" min="0" name="taux_tva"
                    placeholder="Entrer le taux tva de la catégorie..." autocomplete="off" required="required"
                    value="{{categorie.taux_tva}}">
            </div>
            <div class="pb-3">
                <label for="nom">Image</label>
                <br>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="col-md-9">
                        <input class="form-control input_new_categorie" id="image_categorie" type="text" name="image"
                            placeholder="Entrer l'URL de l'image de la categorie..." autocomplete="off"
                            required="required" value="{{categorie.image}}">
                    </div>
                    <div class="col-md-2 offset-md-1 border border-dark">
                        <img id="categorie-img" src="" alt="Entrer un lien pour afficher l'image"
                            title="Pré-visualisation" width="100">
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-outline-warning" type="submit">Modifier</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
{% load static %}
<script src="{% static 'administration/js/image_categorie.js' %}"></script>
{% endblock %}

V2/administration/templates/administration/admin_index.html
{% extends 'administration/admin_base.html' %}
{% load static %}
{% block title %}
Index
{% endblock %}

{% block active_accueil %}
active
{% endblock %}

{% block content %}
<div class="col-md-8 offset-md-2 pt-5">
    <h2>Bonjour M. {{request.user.last_name|upper}},</h2>
    <p class="py-3">Que souhaitez-vous faire ?</p>
</div>
<br>
<div class="card ms-auto me-4 my-4" style="width: 12rem;">
    <a href="{% url 'administration:produits' %}">
        <div class="card-image">
            <img src="{% static 'administration/images/admin_index_produits.png' %}" class="card-img-top" alt="Produits" width="150">
        </div>
    </a>
    <div class="card-heading pt-2">
        <div class="card-title text-center d-flex justify-content-center">
            <h4>Produits</h4>
        </div>
    </div>
    <a href="{% url 'administration:produits' %}" class="btn btn-dark d-flex justify-content-center my-2">Consulter</a>
</div>

<div class="card m-auto my-4" style="width: 12rem;">
    <a href="{% url 'administration:categories' %}">
        <div class="card-image">
            <img src="{% static 'administration/images/admin_index_rayons.png' %}" class="card-img-top" alt="Produits" width="150">
        </div>
    </a>
    <div class="card-heading pt-2">
        <div class="card-title text-center d-flex justify-content-center">
            <h4>Catégories</h4>
        </div>
    </div>
    <a href="{% url 'administration:categories' %}" class="btn btn-dark d-flex justify-content-center my-2">Consulter</a>
</div>

<div class="card m-auto my-4" style="width: 12rem;">
    <a href="{% url 'administration:marques' %}">
        <div class="card-image">
            <img src="{% static 'administration/images/admin_index_marques.png' %}" class="card-img-top" alt="Produits" width="150">
        </div>
    </a>
    <div class="card-heading pt-2">
        <div class="card-title text-center d-flex justify-content-center">
            <h4>Marques</h4>
        </div>
    </div>
    <a href="{% url 'administration:marques' %}" class="btn btn-dark d-flex justify-content-center my-2">Consulter</a>
</div>

<div class="card ms-4 me-auto my-4" style="width: 12rem;">
    <a href="{% url 'administration:clients' %}">
        <div class="card-image">
            <img src="{% static 'administration/images/admin_index_clients.png' %}" class="card-img-top" alt="Produits" width="150">
        </div>
    </a>
    <div class="card-heading pt-2">
        <div class="card-title text-center d-flex justify-content-center">
            <h4>Clients</h4>
        </div>
    </div>
    <a href="{% url 'administration:clients' %}" class="btn btn-dark d-flex justify-content-center my-2">Consulter</a>
</div>
{% endblock %}

V2/administration/templates/administration/admin_marques.html
{% extends 'administration/admin_base.html' %}

{% block title %}
Marques
{% endblock %}

{% block active_marques %}
active
{% endblock %}

{% block content %}

<div class="col-md-10 offset-md-1 pt-5">
    <div class="py-3">
        <h3>Ajouter une marque</h3>
        <hr>
        <div class="text-center">
            <a href="{% url 'administration:marques_ajouter' %}" class="btn btn-outline-success">Ajouter</a>
        </div>
    </div>
    <div class="py-3">
        <h3>Toutes les marques</h3>
        <hr>
        <table class="table table-striped table-hover text-center">
            <thead class="table table-dark">
                <th>ID</th>
                <th>Nom</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </thead>
            <tbody>
                {% for marque in marques %}
                <tr>
                    <td>{{ marque.id}}</td>
                    <td>{{ marque.nom }}</td>
                    <td><a href="{% url 'administration:marques_modifier' marque.id %}" class="btn btn-outline-warning">Modifier</a></td>
                    <td><a href="{% url 'administration:marques_supprimer' marque.id %}" class="btn btn-outline-danger">Supprimer</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

V2/administration/templates/administration/admin_produits.html
{% extends 'administration/admin_base.html' %}

{% block title %}
Produits
{% endblock %}

{% block active_produits %}
active
{% endblock %}

{% block content %}

<div class="col-md-10 offset-md-1 pt-5">
    <div class="py-3">
        <h3>Ajouter un produit</h3>
        <hr>
        <div class="text-center">
            <a href="{% url 'administration:produits_ajouter' %}" class="btn btn-outline-success">Ajouter</a>
        </div>
    </div>
    <div class="py-3">
        <h3>Tous les produits</h3>
        <hr>
        <table class="table table-striped table-hover text-center">
            <thead class="table table-dark">
                <th>Image</th>
                <th>ID</th>
                <th>Nom</th>
                <th>Prix</th>
                <th>Marque</th>
                <th>Catégorie</th>
                <th>Quantité</th>
                <th>Modifier</th>
            </thead>
            <tbody>
                {% for produit in produits %}
                <tr>
                    <td><img src="{{ produit.image }}" alt="{{ produit.nom }}" width="50" height="50" loading="lazy"></td>
                    <td>{{ produit.id }}</td>
                    <td>{{ produit.nom }}</td>
                    <td>{{ produit.calcTVA }}€</td>
                    <td>{{ produit.marque.nom }}</td>
                    <td>{{ produit.categorie.nom }}</td>
                    <td>{{ produit.quantite }}</td>
                    <td><a href="{% url 'administration:produits_detail' produit.id %}" class="btn btn-outline-primary">Modifier</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

V2/administration/templates/administration/admin_produits_detail.html
{% extends 'administration/admin_base.html' %}

{% block title %}
Detail
{% endblock %}

{% block active_produits %}
active
{% endblock %}

{% block content %}
<section>
    <div class="container-fluid px-xl-7 pt-5 pb-3 pb-lg-6">
        <ul class="breadcrumb undefined">
            <li class="breadcrumb-item"><a href="{% url 'administration:index' %}">Accueil</a></li>
            <li class="breadcrumb-item"><a href="{% url 'administration:produits' %}">Produits</a></li>
            <li class="breadcrumb-item active">{{ produit.nom }}</li>
        </ul>
        <div class="row">
            <div class="col-lg-6 col-xl-7 pt-4 order-2 order-lg-1 photoswipe-gallery">
                <div data-toggle="zoom" style="position: relative; overflow: hidden;">
                    <img class="img-fluid" src="{{ produit.image }}" alt="{{ produit.nom }}">
                </div>
            </div>
            <div class="col-lg-6 col-xl-4 pt-4 order-1 order-lg-2 ms-lg-auto">
                <div class="sticky-top" style="top: 100px;">
                    <h2 class="mb-4">{{ produit.nom }}</h2>
                    <div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-sm-between mb-4">
                        <ul class="list-inline mb-2 mb-sm-0">
                            <li class="list-inline-item h4 fw-light mb-0">{{ produit.marque.nom }} -</li>
                            <li class="list-inline-item h4 fw-light mb-0">{{ produit.getPoids }}</li>
                            <br>
                            <li class="list-inline-item h4 fw-light mb-0">{{ produit.calcTVA }}€ -</li>
                            <li class="list-inline-item h4 fw-light mb-0">{{ produit.calcPrixPoids }}</li>
                        </ul>
                        <div class="d-flex align-items-center text-sm">
                            <ul class="list-inline me-2 mb-0">
                                <li class="list-inline-item me-0"><i class="fa fa-star text-primary"></i></li>
                                <li class="list-inline-item me-0"><i class="fa fa-star text-primary"></i></li>
                                <li class="list-inline-item me-0"><i class="fa fa-star text-primary"></i></li>
                                <li class="list-inline-item me-0"><i class="fa fa-star text-primary"></i></li>
                                <li class="list-inline-item me-0"><i class="fa fa-star text-gray-300"></i></li>
                            </ul>
                        </div>
                    </div>
                    <p class="mb-4 text-muted">{{ produit.description }}</p>
                    {% if produit.achetable == 1 %}
                    <ul class="list-inline mb-2 mb-sm-0">
                        <li class="list-inline-item fw-light mb-0">En stock: {{ produit.stock }}</li>
                        <li class="list-inline-item fw-light mb-0"><a
                                href="{% url 'administration:produits_modifier_stock' produit.id %}"
                                class="btn btn-outline-primary">Modifier
                                le stock</a></li>
                    </ul>
                    <div class="py-3">
                        <a href="{% url 'administration:produits_modifier' produit.id %}"
                            class="btn btn-outline-warning">Modifier
                            le produit</a>
                        <br>
                        <br>
                        <a href="{% url 'administration:produits_supprimer' produit.id %}"
                            class="btn btn-outline-danger">Supprimer</a>
                    </div>
                    {% else %}
                    <h3 class="text-danger">Ce produit n'est plus disponible.</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}