V2/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
]

V2/bio_et_terre/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path, path

from store import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('administration/', include('administration.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [re_path(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

V2/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('account/', views.account, name="account"),
    path('histCommande/<int:id>', views.historiqueCommande, name="historiqueCommande"),
    path('panier/', views.panier, name="panier"),
    path('panierModifQtt/', views.panierModifierQuantite, name="panierModifierQuantite"),
    path('rayons/', views.rayons, name="rayons"),
    path('rayons/<int:id>', views.rayons_listing, name="rayon_listing"),
    path('recherche/', views.recherche, name="recherche"),
    path('produit/<str:id>', views.produit_detail, name="produit_detail"),
]

V2/accounts/models.py
from django.contrib.auth.models import AbstractUser

class Utilisateur(AbstractUser):
    pass

V2/accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, login, authenticate, logout
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.shortcuts import render, redirect

User = get_user_model()
# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == "POST":
        valide = True
        firstname = request.POST.get("firstname")
        lastname = request.POST.get("lastname")
        email = request.POST.get("email")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")

        try:
            validate_email(email)
        except ValidationError as error:
            valide = False
            for e in error:
                messages.error(request, e)

        queryUser = User.objects.filter(email=email)
        if queryUser:
            valide = False
            messages.error(request, "Cette adresse mail est déjà utilisée.")

        if password != confirm_password:
            valide = False
            messages.error(request, "Saisissez deux fois le même mot de passe.")

        if valide:
            user = User.objects.create_user(username=email, password=password, first_name=firstname, last_name=lastname, email=email)
            login(request, user)
            return redirect('index')

    return render(request, 'accounts/signup.html')


def login_user(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        queryUser = User.objects.filter(email=email)
        if queryUser:
            user = authenticate(username=email, password=password)
            if user:
                login(request, user)
                return redirect('index')
            else:
                messages.error(request, "Mauvais mot de passe.")
        else:
            messages.error(request, "Aucun compte ne correspond à cette adresse mail.")

    return render(request, 'accounts/login.html')


def logout_user(request):
    logout(request)
    return redirect('index')

V2/accounts/templates/accounts/login.html
{% extends 'store/base.html' %}

{% block title %}Se connecter{% endblock %}

{% block content %}
<div class="col-md-6 offset-3 py-5">
    <h3>Se connecter</h3>
    <hr>
    <form method="POST">
        {% csrf_token %}

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}

        <div class="pb-3">
            <label for="email">Adresse mail</label>
            <br>
            <input class="form-control" id="email" type="email" name="email" placeholder="Entrez votre adresse mail..." autocomplete="off" required="required">
        </div>

        <div class="pb-3">
            <label for="password">Mot de passe</label>
            <br>
            <input class="form-control" id="password" type="password" name="password" placeholder="Entrez votre mot de passe..." autocomplete="off" required="required">
        </div>

        <button class="btn btn-primary btn-block" type="submit">Se connecter</button>
    </form>

    <div class="py-3">
        <a href="{% url 'accounts:signup' %}">Je n'ai pas de compte...</a>
    </div>
</div>
{% endblock %}

V2/accounts/templates/accounts/signup.html
{% extends 'store/base.html' %}

{% block title %}S'inscrire{% endblock %}

{% block content %}
<div class="col-md-6 offset-3 py-5">
    <h3>S'inscrire</h3>
    <hr>
    <form method="POST">
        {% csrf_token %}

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}

        <div class="pb-3">
            <label for="firstname">Prénom</label>
            <br>
            <input class="form-control" id="firstname" type="text" name="firstname" placeholder="Entrez votre prénom..." autocomplete="off" required="required">
        </div>

        <div class="pb-3">
            <label for="lastname">Nom</label>
            <br>
            <input class="form-control" id="lastname" type="text" name="lastname" placeholder="Entrez votre nom..." autocomplete="off" required="required">
        </div>

        <div class="pb-3">
            <label for="email">Adresse mail</label>
            <br>
            <input class="form-control" id="email" type="email" name="email" placeholder="Entrez votre adresse mail..." autocomplete="off" required="required">
        </div>

        <div class="pb-3">
            <label for="password">Mot de passe</label>
            <br>
            <input class="form-control" id="password" type="password" name="password" placeholder="Entrez votre mot de passe..." autocomplete="off" required="required">
        </div>

        <div class="pb-3">
            <label for="confirm_password">Confirmer mot de passe</label>
            <br>
            <input class="form-control" id="confirm_password" type="password" name="confirm_password" placeholder="Confirmez votre mot de passe..." autocomplete="off" required="required">
        </div>

        <button class="btn btn-primary btn-block" type="submit">S'inscrire</button>
    </form>

    <div class="py-3">
        <a href="{% url 'accounts:login' %}">J'ai déjà un compte...</a>
    </div>
</div>
{% endblock %}