V1/Projet_S3_Commerce/urls.py
from django.conf import settings
from django.conf.urls import url, include
# from django.contrib import admin
from django.urls import path

from store import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', include('admin.urls')),
    #url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

V1/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True, authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html', next_page='accounts:login'), name='logout'),
]

V1/admin/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'admin'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('produits/', views.produits, name="produits"),
    path('produits/ajouter/', views.produits_ajouter, name="produits_ajouter"),
    url(r'^produits/(?P<produit_id>[0-9]+_[0-9]+)/$', views.produits_detail, name='produits_detail'),
    url(r'^produits/modif/(?P<produit_id>[0-9]+_[0-9]+)/$', views.produits_modif, name='produits_modif'),
    url(r'^produits/modif_stock/(?P<produit_id>[0-9]+_[0-9]+)/$', views.produits_modif_stock, name='produits_modif_stock'),
    path('updateQtt/', views.updateQtt, name="updateQtt"),
    path('update/', views.update, name="update"),
    path('ajouter/', views.ajouter, name="ajouter"),
    path('delete/', views.delete, name="delete"),
    path('categories/', views.categories, name='categories'),
    path('categories/ajouter/', views.ajouter_categories, name='ajouter_categories'),
    path('categories_add/', views.add_categories, name='add_categories'),
    url(r'^categories/modif/(?P<id>[0-9]+)/$', views.modifier_categories, name='modifier_categories'),
    path('update_categorie/', views.update_categories, name='update_categories'),
    url(r'^categories/suppr/(?P<id>[0-9]+)/$', views.delete_categories, name='delete_categories'),
    path('categories/suppr/', views.suppr_categories, name='suppr_categories'),
    path('marques/', views.marques, name='marques'),
    path('marques/ajouter/', views.ajouter_marques, name='ajouter_marques'),
    path('marques_add/', views.add_marques, name='add_marques'),
    url(r'^marques/modif/(?P<id>[0-9]+)/$', views.modifier_marques, name='modifier_marques'),
    path('update_marque/', views.update_marques, name='update_marques'),
    url(r'^marques/suppr/(?P<id>[0-9]+)/$', views.delete_marques, name='delete_marques'),
    path('marques/suppr/', views.suppr_marques, name='suppr_marques'),
    path('clients/', views.clients, name="clients"),
]

V1/store/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    url(r'^rayon/$', views.rayon, name='rayon'),
    url(r'^rayon/(?P<categorie_id>[0-9]+)/$', views.rayon_listing, name='rayon_listing'),
    url(r'^(?P<produit_id>[0-9]+_[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<produit_id>[0-9]+_[0-9]+)/(?P<produit_qtt>[0-9]+)$', views.ajout_panier, name='ajout_panier'),
    url(r'^panier/', views.panier, name="panier"),
    url(r'^search/$', views.search, name='search'),
    path('update_item/', views.updateItem, name="update_item"),
    path('valider_commande/', views.validerCommande, name="valider_commande"),
    path('account/', views.account, name="account"),
    url('^account/detail_commande/(?P<panier_id>[0-9]+)$', views.detail_commande, name="detail_commande")
]

V1/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

User = get_user_model()

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Adresse mail', required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder': 'Entrez votre adresse mail...'}))
    password = forms.CharField(label='Mot de passe', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder': 'Entrez votre mot de passe...'}))

class UserForm(UserCreationForm):
    first_name = forms.CharField(label='Prénom', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder': 'Entrez votre prénom...'}))
    last_name = forms.CharField(label='Nom', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder': 'Entrez votre nom de famille...'}))
    email = forms.CharField(label='Adresse mail', required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder': 'Entrez votre adresse mail...'}))
    password1 = forms.CharField(label='Mot de passe', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder': 'Entrez votre mot de passe...'}))
    password2 = forms.CharField(label='Vérification du mot de passe', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder': 'Confirmez votre mot de passe...'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

V1/accounts/views.py
from django.shortcuts import render, redirect

from .forms import UserForm


# Create your views here.
def login(request):
    if request.user.is_superuser:
        return redirect('admin/index.html')

def register(request):
    if request.user.is_authenticated:
            return redirect('index')

    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            form.save()

    else:
        form = UserForm()

    context = {
        'form': form
    }

    return render(request, 'accounts/register.html', context)

V1/store/views.py
import datetime
import json
import random

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.db import connection
from django.db.models import Q
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.template import loader

from accounts.models import User
from .models import Produit, Categorie, Commande, EstComposeDe, Panier


# Create your views here.
# @login_required mettre ça quand être login est necessaire
@login_required()
def account(request):
    template = loader.get_template("store/account.html")

    client = User.objects.get(id=request.user.id)
    commande = Commande.objects.filter(id_utilisateur=request.user.id, id_panier__valide=1).order_by("id_panier")
    produits = EstComposeDe.objects.all()
    context = {
        'client': client,
        'commande': commande,
        'produits': produits,
    }

    return HttpResponse(template.render(context, request=request))

def detail_commande(request, panier_id):
    template = loader.get_template("store/detail_commande.html")

    commande = Commande.objects.filter(id_utilisateur=request.user.id, id_panier=panier_id)
    if commande:
        if commande[0].id_panier.valide == 1:
            panier = EstComposeDe.objects.filter(id_panier=panier_id, id_panier__valide=1)
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    context = {
        'commande': commande[0],
        'produits': panier,
    }

    return HttpResponse(template.render(context, request=request))

def index(request):
    template = loader.get_template("store/index.html")
    prods = Produit.objects.order_by("id")

    if request.user.is_superuser:
        template = loader.get_template("admin/admin_index.html")
        context = {}
        return HttpResponse(template.render(context, request=request))

    produits = []
    already_took = []
    for i in range(9):
        rand = random.randrange(0, len(prods))
        while rand in already_took and prods[rand].achetable == 0:
            rand = random.randrange(0, len(prods))

        already_took.append(rand)
        produits.append(prods[rand])

    context = {
        "produits": produits
    }

    return HttpResponse(template.render(context, request=request))


def rayon(request):
    template = loader.get_template("store/rayon.html")

    context = {
        'rayons': Categorie.objects.raw("SELECT * FROM commerce.categorie WHERE id IN (SELECT id_categorie FROM commerce.produit WHERE qtt_stock > 0) ORDER BY nom;")
    }

    return HttpResponse(template.render(context, request=request))


def rayon_listing(request, categorie_id):
    template = loader.get_template("store/rayon_listing.html")
    context = {
        'produits': Produit.objects.filter(categorie=categorie_id, achetable=1).order_by("nom").exclude(qtt_stock=0)
    }
    return HttpResponse(template.render(context, request=request))


def detail(request, produit_id):
    template = loader.get_template("store/detail.html")

    context = {
        'produit': Produit.objects.get(pk=produit_id)
    }
    return HttpResponse(template.render(context, request=request))


#@login_required()
def panier(request):
    template = loader.get_template("store/panier.html")

    if request.user.is_authenticated:
        client = User.objects.get(id=request.user.id)

        # SELECTION/CREATION COMMANDE ET PANIER
        commande = Commande.objects.filter(id_utilisateur=client.id, id_panier__valide=False)
        if commande:
            commande = commande[0]
            panier = commande.id_panier
        else:
            panier_id_max = Panier.objects.values_list('id').order_by('-id')
            if panier_id_max:
                panier = Panier.objects.create(id=panier_id_max[0][0] + 1)
            else:
                panier = Panier.objects.create(id=1)

            commande = Commande.objects.create(id_utilisateur=client, id_panier=panier)

        produits = EstComposeDe.objects.filter(id_panier=panier).order_by('id_produit__categorie')
    else:
        produits = []

    context = {
        'commande': commande,
        'produits': produits
    }
    return HttpResponse(template.render(context, request=request))

def ajout_panier(request, produit_id, produit_qtt):
    template = loader.get_template("store/detail.html")
    context = {
        'produit': Produit.objects.get(pk=produit_id),
        'quantite': produit_qtt
    }
    return HttpResponse(template.render(context, request=request))

def search(request):
    query = request.GET.get('query')
    if not query:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    else:
        produits = Produit.objects.filter(Q(nom__icontains=query) | Q(descript__icontains=query) | Q(marque__nom__icontains=query) | Q(categorie__nom__icontains=query)).filter(achetable=1).order_by("categorie")
        categories = Categorie.objects.filter(nom__icontains=query).order_by("id")
    context = {
        'query': query,
        'produits': produits,
        'categories':categories,
    }

    template = loader.get_template("store/search.html")
    return HttpResponse(template.render(context, request=request))

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    qtt = data['quantite']

    produit = Produit.objects.get(id=productId)
    client = User.objects.get(id=request.user.id)

    # SELECTION/CREATION COMMANDE ET PANIER
    commande = Commande.objects.filter(id_utilisateur=client.id, id_panier__valide=False)
    if commande:
        commande = commande[0]
        panier = commande.id_panier
    else:
        panier_id_max = Panier.objects.values_list('id').order_by('-id')
        if panier_id_max:
            panier = Panier.objects.create(id= panier_id_max[0][0] + 1)
        else:
            panier = Panier.objects.create(id=1)

        commande = Commande.objects.create(id_utilisateur=client, id_panier=panier)

    # SELECTION/CREATION COMPOSITION
    composition = EstComposeDe.objects.filter(id_produit=produit, id_panier=panier)
    if composition:
        composition = composition[0]
    else:
        composition = EstComposeDe.objects.create(id_produit=produit, id_panier=panier, quantite=0)

    quant = 0
    if action == "add":
        quant = composition.quantite + qtt
    elif action == "delete":
        quant = composition.quantite - 1

    if quant > composition.id_produit.qtt_stock:
        quant = composition.id_produit.qtt_stock

    with connection.cursor() as cursor:
        cursor.execute("UPDATE commerce.est_compose_de SET quantite=%s WHERE id_produit=%s AND id_panier=%s", [quant, composition.id_produit.id, composition.id_panier.id])

    if quant <= 0:
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM commerce.est_compose_de WHERE id_produit=%s AND id_panier=%s AND quantite <= 0", [composition.id_produit.id, composition.id_panier.id])

    return JsonResponse("Article ajouté", safe=False)

def validerCommande(request):

    if request.user.is_authenticated:
        client = User.objects.get(id=request.user.id)
        commande = Commande.objects.get(id_utilisateur=client.id, id_panier__valide=False)
        if commande:
            panier = commande.id_panier
            composition = EstComposeDe.objects.filter(id_panier=panier).order_by('id_produit__categorie')
            for comp in composition:
                prod = comp.id_produit
                prod.qtt_stock = prod.qtt_stock - comp.quantite
                prod.save()

            panier.valide = 1
            panier.save()

            date = datetime.datetime.now()
            commande.date_validation = date.strftime("%Y-%m-%d %H:%M:%S")
            commande.save()

            sujet = "Merci pour votre commande !"
            message = """<!DOCTYPE html>
                        <html lang="en">
                        
                        <head>
                            <meta charset="UTF-8">
                            <meta http-equiv="X-UA-Compatible" content="IE=edge">
                            <meta name="viewport" content="width=device-width, initial-scale=1.0">
                            <title>Merci pour votre commande !</title>
                            <style>
                                .box-element {
                                    box-shadow: hsl(0, 0%, 80%) 0 0 16px;
                                    background-color: #fff;
                                    border-radius: 4px;
                                    padding: 10px;
                                }
                        
                                .row-image {
                                    width: 100px;
                                }
                        
                                .cart-row {
                                    display: flex;
                                    align-items: flex-stretch;
                                    padding-bottom: 10px;
                                    margin-bottom: 10px;
                                    border-bottom: 1px solid #ececec;
                        
                                }
                        
                                .quantity {
                                    display: inline-block;
                                    font-weight: 700;
                                    padding-right: 10px;
                        
                        
                                }
                        
                                .chg-quantity {
                                    width: 12px;
                                    cursor: pointer;
                                    display: block;
                                    margin-top: 5px;

V1/store/templates/store/account.html
{% extends 'store/base.html' %}

{% block title %}
Compte
{% endblock %}

{% block content %}
<div class="col-md-8 offset-md-2 py-3">
    <h2>Mon compte</h2>
    <hr>
    <div class="pb-3">
        Prénom
        <br>
        <input class="form-control" id="disabledInput" type="text" placeholder="{{ client.first_name|title }}" disabled>
    </div>
    <div class="pb-3">
        Nom
        <br>
        <input class="form-control" id="disabledInput" type="text" placeholder="{{ client.last_name|title }}" disabled>
    </div>
    <div class="pb-3">
        Adresse mail
        <br>
        <input class="form-control" id="disabledInput" type="text" placeholder="{{ client.email }}" disabled>
    </div>

    <div class="text-center bg-danger rounded-pill my-3">
        <a class="nav-link text-light" href="{% url 'accounts:logout' %}">Me déconnecter</a>
    </div>
</div>

<div class="col-md-8 offset-md-2 py-3">
    <h2>Mes commandes</h2>
    <hr>
    {% if commande %}
    <table class="table text-center table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Numéro de commande</th>
                <th>Date & Heure </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for com in commande %}
            <tr>
                <td>{{com.id_panier.id}}</td>
                <td>{{com.date_validation}}</td>
                <td><a class="btn btn-dark" href="{% url 'store:detail_commande' com.id_panier.id %}">Consulter</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
    <div class="text-center py-3">
        Vous n'avez passé aucune commande pour le moment.
    </div>
    {% endif %}
</div>

{% endblock %}

V1/store/templates/store/base.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Bio&Terre - {% block title %}{% endblock %}</title>
  <link rel="icon" href="{% static 'store/logo.ico' %}" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script type="text/javascript">
    var user = '{{request.user}}'

    function getToken(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
          const cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }

    const csrftoken = getToken('csrftoken');
    const urlUpdateItem = "{% url 'store:update_item'%}"
  </script>
</head>

<body class="d-flex flex-column" style="min-height: 100vh;">
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'store/Logo_Blanc.png'%}" alt="Bio & Terre"
            width="75" height="75"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
          aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item px-2">
              <a class="nav-link {% block active_accueil %}{% endblock %}" href="{% url 'index' %}">Accueil</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link {% block active_rayons %}{% endblock %}" href="{% url 'store:rayon' %}">Rayons</a>
            </li>
            <li class="nav-item px-2">
              <form action="{% url 'store:search' %}" method="get">
                  <input class="form-control" name="query" type="text" placeholder="Rechercher..." aria-label="Search">
              </form>
            </li>
          </ul>
          {% if request.user.is_authenticated %}
          <div class="d-inline-flex px-2">
            <a href="{% url 'store:account' %}"><img src="{% static 'store/user.png' %}" title="Mon compte" alt="Mon Compte" height="30" width="30"></a>
          </div>
          <div class="d-inline-flex px-2">
            <a href="{% url 'store:panier' %}"><img src="{% static 'store/shopping-cart.png' %}" title="Panier" alt="Panier" height="30" width="30"></a>
          </div>
          {% else %}
          <div class="d-inline-flex bg-success rounded-pill">
            <a class="nav-link text-light" href="{% url 'accounts:login' %}">Se connecter</a>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

  <div class="container">
    <div class="row">
      {% block content%}{% endblock %}
    </div>
  </div>

  <footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <div>
        <p class="my-1 text-muted text-center">Site web réalisé à l'aide du framework Django par:</p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted text-center"
            href="mailto:mathieu.dary@etudiant.univ-rennes1.fr">mathieu.dary@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted text-center"
            href="mailto:erwann.gauthier@etudiant.univ-rennes1.fr">erwann.gauthier@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted"
            href="mailto:titouan.le-berre@etudiant.univ-rennes1.fr">titouan.le-berre@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
      <div>
        <p class="my-1 text-center">
          <a class="text-muted"
            href="mailto:yannis.ligot@etudiant.univ-rennes1.fr">yannis.ligot@etudiant.univ-rennes1.fr</a>
        </p>
      </div>
    </div>
  </footer>


  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

  <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
  {% block linkJs %}{% endblock %}
</body>

</html>

V1/store/templates/store/panier.html
{% extends 'store/base.html' %}

{% block title %}
Panier
{% endblock %}

{% block active_panier%}
active
{% endblock %}

{% block content %}
{% load static %}
<div class="col-lg-12">
    <br>
    <br>

    <div class="box-element">
        <a class="btn btn-outline-dark" href="{% url 'store:rayon' %}">&#x2190; Continuer mes achats</a>

        <br>
        <br>

        <table class="table">
            <tr>
                <th>
                    <h5>Articles: <strong>{{commande.get_cart_items}}</strong> dont {{produits.count}} différent{% if produits.count > 1 %}s{% endif %}</h5>
                </th>
                <th>
                    <h5>Total: <strong>{{commande.get_cart_total}}€</strong></h5>
                </th>
                <th>
                    {% if produits %}
                    <a style="float:right; margin: 5px;" class="btn btn-success" href="{% url 'store:valider_commande' %}">Payer</a>
                    {% else %}
                    <a style="float:right; margin: 5px;" class="btn btn-secondary disabled" href="">Payer</a>
                    {% endif %}
                </th>
            </tr>
        </table>
    </div>

    <br>

    <div class="box-element">
        {% if produits %}
        <div class="cart-row">
            <div style="flex:2"><strong>Image</strong></div>
            <div style="flex:2"><strong>Article</strong></div>
            <div style="flex:1"><strong>Prix</strong></div>
            <div style="flex:1"><strong>Quantité</strong></div>
            <div style="flex:1"><strong>Total</strong></div>
        </div>

        {% for produit in produits %}
        <div class="cart-row">
            <div style="flex:2"><a href="{% url 'store:detail' produit.id_produit.id %}"><img src="{{produit.id_produit.image}}" alt="{{produit.id_produit.nom}}" height="75" width="75"></a></div>
            <div style="flex:2">
                <p>{{produit.id_produit.nom}}</p>
            </div>
            <div style="flex:1">
                <p>{{produit.id_produit.prix}}€</p>
            </div>
            <div style="flex:1">
                <p class="quantity">{{produit.quantite}}</p>
                <div class="quantity">
                    {% if produit.quantite < produit.id_produit.qtt_stock %}
                    <img data-product="{{produit.id_produit.id}}" data-action="add" src="{% static 'store/up-arrow.png' %}" alt="" class="chg-quantity update-cart">
                    {% endif %}
                    <img data-product="{{produit.id_produit.id}}" data-action="delete" src="{% static 'store/down-arrow.png' %}" alt="" class="chg-quantity update-cart">
                </div>
            </div>
            <div style="flex:1">
                <p>{{produit.calcPrixTotal}}€</p>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="cart-row justify-content-md-center">
            <p><strong>Votre panier est vide !</strong></p>
        </div>
        {% endif %}
    </div>

    <br>
</div>

{% endblock %}

V1/store/templates/store/rayon.html
{% extends 'store/base.html' %}

{% block title %}
Rayons
{% endblock %}

{% block active_rayons %}
active
{% endblock %}

{% block content %}

<div class="container-fluid px-xl-7 pt-5 pb-3 pb-lg-6">
    <ul class="breadcrumb undefined">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Accueil</a></li>
        <li class="breadcrumb-item active">Rayons</li>
    </ul>
</div>

{% for rayon in rayons %}
<div class="card h-100 mx-auto my-4" style="width: 12rem;">
    <a href="{% url 'store:rayon_listing' rayon.id %}">
        <img src="{{ rayon.image }}" class="card-img-top" alt="{{ rayon.nom }}">
    </a>
    <div class="card-body">
        <a href="{% url 'store:rayon_listing' rayon.id %}"
            class="card-title btn btn-dark text-center d-flex justify-content-center">{{ rayon.nom }}</a>
    </div>
</div>
{% endfor %}
{% endblock %}

V1/store/templates/store/rayon_listing.html
{% extends 'store/base.html' %}

{% block title %}
Rayon Listing
{% endblock %}

{% block active_rayons%}
active
{% endblock %}

{% block content %}

<div class="container-fluid px-xl-7 pt-5 pb-3 pb-lg-6">
    <ul class="breadcrumb undefined">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Accueil</a></li>
        <li class="breadcrumb-item"><a href="{% url 'store:rayon' %}">Rayons</a></li>
        <li class="breadcrumb-item active">{{ produits.0.categorie.nom }}</li>
    </ul>
</div>

{% if produits %}
{% for produit in produits %}

<div class="card mx-auto my-4" style="width: 12rem;">
    <a href="{% url 'store:detail' produit.id %}">
        <div class="card-image">
            <img src="{{ produit.image }}" class="card-img-top" alt="{{ produit.nom }}">
        </div>
    </a>
    <div class="card-heading">
        <div class="card-title text-center d-flex justify-content-center">
            {{ produit.nom }}
        </div>
    </div>
    <div class="card-text text-muted">{{ produit.calcTVA }}€</div>
    <div class="card-text text-muted">
        {% with type=produit.calcPrixType %}
        {{ type.0 }}€/{{ type.1 }}
        {% endwith %}
    </div>
    <a href="{% url 'store:detail' produit.id %}" class="btn btn-dark d-flex justify-content-center my-2">Acheter</a>
</div>

{% endfor %}
{% else %}
<div class="row justify-content-md-center">
    <div class="col-md-8 col-md-offset-2 mb-5 text-center">
        <p>Il semblerait que ce rayon soit victime de son succès ! Aucun article n’est disponible ici...</p>
        <img src="https://c.tenor.com/tlYo239ITUMAAAAM/sad-tears.gif" alt="GIF Triste">
    </div>
</div>
{% endif %}
{% endblock %}